version: '3'
services:
  client:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '4200:4200'
    volumes:
      - /app/node_modules
      - ./src:/frontend/src
    command: npm start
